apiVersion: v1
kind: Service
metadata:
  name: hello-flask
spec:
  type: NodePort
  selector:
    app: hello-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 5000

